export const obsidianSceneStyles = {
  scene:
    'relative isolate min-h-screen overflow-hidden bg-[radial-gradient(circle_at_50%_38%,rgb(var(--accent-hot-rgb)/0.22),transparent_34%),radial-gradient(circle_at_80%_20%,rgb(var(--accent-rgb)/0.16),transparent_28%),radial-gradient(circle_at_18%_78%,rgb(var(--accent-hot-rgb)/0.12),transparent_32%),linear-gradient(180deg,var(--liquid-bg),color-mix(in_srgb,var(--liquid-bg)_88%,#000_12%))] text-[var(--text)] [contain:layout_paint_style] before:pointer-events-none before:absolute before:inset-[clamp(14px,2vw,28px)] before:z-0 before:bg-[linear-gradient(90deg,rgb(var(--accent-hot-rgb)/0.035)_1px,transparent_1px),linear-gradient(rgb(var(--accent-hot-rgb)/0.03)_1px,transparent_1px)] before:bg-[length:42px_42px] before:opacity-70 before:content-[""] after:pointer-events-none after:absolute after:top-[52%] after:left-1/2 after:z-0 after:size-[min(72vw,780px)] after:-translate-x-1/2 after:-translate-y-1/2 after:rounded-full after:bg-[radial-gradient(circle_at_var(--mouse-x,50%)_var(--mouse-y,50%),var(--liquid-glow),transparent_18%),conic-gradient(from_130deg,transparent,rgb(var(--accent-hot-rgb)/0.12),transparent_42%)] after:opacity-75 after:[filter:blur(1px)] after:content-[""] max-[760px]:min-h-[100svh] max-[760px]:overflow-x-hidden max-[760px]:overflow-y-auto platform-windows:after:[filter:none] platform-ios:!h-dvh platform-ios:!min-h-dvh platform-ios:!overflow-hidden platform-ios:after:!hidden',
  stage:
    'relative z-[1] grid h-screen min-h-screen grid-cols-1 grid-rows-[auto_minmax(0,1fr)] gap-3.5 overflow-hidden px-[14px] pt-16 pb-[14px] [backface-visibility:hidden] [transform:translateZ(0)] min-[761px]:px-[18px] min-[761px]:pt-[86px] min-[761px]:pb-[18px] max-[760px]:h-auto max-[760px]:min-h-[100svh] max-[760px]:gap-2.5 max-[760px]:overflow-visible max-[760px]:px-2 max-[760px]:pt-[calc(62px+env(safe-area-inset-top))] max-[760px]:pb-[calc(82px+env(safe-area-inset-bottom))] platform-ios:!h-dvh platform-ios:!min-h-dvh platform-ios:!overflow-hidden platform-ios:!px-2 platform-ios:!pt-[calc(8px+env(safe-area-inset-top))] platform-ios:!pb-[calc(var(--mobile-nav-height)+18px+env(safe-area-inset-bottom))]',
  graph:
    'grid h-full min-h-0 w-full min-w-0 grid-rows-[auto_minmax(0,1fr)] gap-2.5 overflow-hidden opacity-100 min-[761px]:min-h-[calc(100dvh-104px)] max-[760px]:overflow-hidden',
  toolbar:
    'grid grid-cols-[auto_minmax(180px,1fr)_auto_auto] items-center gap-2 rounded-[18px] border border-white/9 p-2 shadow-[0_18px_48px_rgba(0,0,0,0.22)] [background:linear-gradient(135deg,rgba(255,255,255,0.12),rgba(255,255,255,0.03)),rgba(27,27,31,0.78)] [backdrop-filter:blur(18px)_saturate(1.18)] max-[760px]:grid-cols-3 platform-windows:shadow-none platform-windows:[backdrop-filter:none] platform-ios:!grid-cols-[minmax(0,1fr)_auto] platform-ios:!rounded-2xl platform-ios:!bg-[#1b1b1f] platform-ios:!shadow-none platform-ios:![backdrop-filter:none]',
  toolbarInput:
    'min-h-[38px] min-w-0 rounded-[13px] border border-white/8 bg-white/[0.055] px-3 text-[13px] text-zinc-100 outline-none placeholder:text-zinc-300/55 max-[760px]:order-first max-[760px]:col-span-full platform-ios:!order-none platform-ios:!col-span-1 platform-ios:!bg-white/[0.08] platform-ios:placeholder:!text-zinc-400',
  toolbarButton:
    'inline-flex min-h-[38px] cursor-pointer items-center justify-center gap-[7px] whitespace-nowrap rounded-[13px] border border-white/10 bg-white/7 px-3 text-xs font-[850] text-zinc-100 transition-[background,border-color,transform] duration-180 hover:-translate-y-px hover:border-yellow-300/20 hover:bg-yellow-300/14 disabled:cursor-not-allowed disabled:opacity-50 max-[760px]:w-full max-[760px]:min-w-0 max-[760px]:px-2 platform-windows:transition-none platform-windows:hover:translate-y-0 platform-ios:!w-auto platform-ios:!border-yellow-300/20 platform-ios:!bg-yellow-300/12 platform-ios:!text-yellow-100',
  fileButton: 'text-yellow-200 max-[430px]:[&>span]:hidden',
  syncButton: 'text-green-300 max-[430px]:[&>span]:hidden',
} as const

export const brainMapStyles = {
  page: [
    'relative grid h-full min-h-0 grid-rows-[auto_minmax(0,1fr)] overflow-hidden rounded-[18px] border border-white/8 bg-[#1f1f22] text-zinc-200 shadow-[0_34px_90px_rgba(0,0,0,0.36)] platform-windows:shadow-none',

    '[&_.eyebrow]:text-[11px] [&_.eyebrow]:text-zinc-400',
    '[&_.obsidian-graph-topbar]:relative [&_.obsidian-graph-topbar]:z-[5] [&_.obsidian-graph-topbar]:flex [&_.obsidian-graph-topbar]:min-h-14 [&_.obsidian-graph-topbar]:items-center [&_.obsidian-graph-topbar]:justify-between [&_.obsidian-graph-topbar]:gap-3.5 [&_.obsidian-graph-topbar]:border-b [&_.obsidian-graph-topbar]:border-white/7 [&_.obsidian-graph-topbar]:bg-zinc-900/94 [&_.obsidian-graph-topbar]:px-3.5 [&_.obsidian-graph-topbar]:py-2.5 max-[760px]:[&_.obsidian-graph-topbar]:flex-col max-[760px]:[&_.obsidian-graph-topbar]:items-stretch max-[760px]:[&_.obsidian-graph-topbar]:gap-2',
    '[&_.obsidian-graph-topbar>div:first-child]:grid [&_.obsidian-graph-topbar>div:first-child]:min-w-0 [&_.obsidian-graph-topbar>div:first-child]:gap-0.5',
    '[&_.obsidian-graph-topbar>div:first-child>strong]:overflow-hidden [&_.obsidian-graph-topbar>div:first-child>strong]:text-ellipsis [&_.obsidian-graph-topbar>div:first-child>strong]:whitespace-nowrap [&_.obsidian-graph-topbar>div:first-child>strong]:text-sm [&_.obsidian-graph-topbar>div:first-child>strong]:text-zinc-100',
    '[&_.obsidian-graph-actions]:flex [&_.obsidian-graph-actions]:min-w-0 [&_.obsidian-graph-actions]:items-center [&_.obsidian-graph-actions]:gap-1.5 max-[760px]:[&_.obsidian-graph-actions]:overflow-x-auto max-[760px]:[&_.obsidian-graph-actions]:pb-0.5',
    '[&_.obsidian-graph-actions_button]:inline-flex [&_.obsidian-graph-actions_button]:min-h-8 [&_.obsidian-graph-actions_button]:cursor-pointer [&_.obsidian-graph-actions_button]:items-center [&_.obsidian-graph-actions_button]:rounded-[10px] [&_.obsidian-graph-actions_button]:border [&_.obsidian-graph-actions_button]:border-white/7 [&_.obsidian-graph-actions_button]:bg-white/[0.045] [&_.obsidian-graph-actions_button]:px-2.5 [&_.obsidian-graph-actions_button]:text-[11px] [&_.obsidian-graph-actions_button]:font-extrabold [&_.obsidian-graph-actions_button]:text-zinc-400 hover:[&_.obsidian-graph-actions_button]:bg-white/9 hover:[&_.obsidian-graph-actions_button]:text-white max-[760px]:[&_.obsidian-graph-actions_button]:shrink-0',
    '[&_.obsidian-graph-actions_button.is-active]:bg-white/9 [&_.obsidian-graph-actions_button.is-active]:text-white',

    '[&_.obsidian-graph-main]:relative [&_.obsidian-graph-main]:min-h-0 [&_.obsidian-graph-main]:overflow-hidden [&_.obsidian-graph-main]:bg-[radial-gradient(circle_at_50%_42%,rgba(250,204,21,0.08),transparent_34%),radial-gradient(circle_at_32%_58%,rgba(34,197,94,0.06),transparent_26%),#202023] max-[760px]:[&_.obsidian-graph-main.has-selection]:grid max-[760px]:[&_.obsidian-graph-main.has-selection]:grid-rows-[minmax(210px,1fr)_minmax(190px,42dvh)]',
    'min-[761px]:[&_.obsidian-graph-main.has-selection]:grid min-[761px]:[&_.obsidian-graph-main.has-selection]:grid-cols-[minmax(0,1fr)_minmax(290px,340px)]',
    '[&_.obsidian-graph-viewport]:relative [&_.obsidian-graph-viewport]:grid [&_.obsidian-graph-viewport]:h-full [&_.obsidian-graph-viewport]:min-h-[620px] [&_.obsidian-graph-viewport]:w-full [&_.obsidian-graph-viewport]:place-items-center max-[760px]:[&_.obsidian-graph-viewport]:min-h-0 max-[760px]:[&_.obsidian-graph-viewport]:overflow-hidden',
    'min-[761px]:[&_.obsidian-graph-main.has-selection_.obsidian-graph-viewport]:col-start-1 min-[761px]:[&_.obsidian-graph-main.has-selection_.obsidian-graph-viewport]:min-w-0',
    '[&_.obsidian-graph-viewport_svg]:block [&_.obsidian-graph-viewport_svg]:h-full [&_.obsidian-graph-viewport_svg]:max-h-full [&_.obsidian-graph-viewport_svg]:w-full [&_.obsidian-graph-viewport_svg]:max-w-full [&_.obsidian-graph-viewport_svg]:cursor-grab [&_.obsidian-graph-viewport_svg]:touch-none [&_.obsidian-graph-viewport_svg]:select-none active:[&_.obsidian-graph-viewport_svg]:cursor-grabbing',
    '[&_.obsidian-graph-boundary]:fill-none [&_.obsidian-graph-boundary]:stroke-yellow-300/20 [&_.obsidian-graph-boundary]:[stroke-dasharray:2_11] [&_.obsidian-graph-boundary]:[stroke-linecap:round] [&_.obsidian-graph-boundary]:[stroke-width:3]',
    '[&_.obsidian-graph-links]:pointer-events-none',
    '[&_.obsidian-graph-links_line]:stroke-zinc-400/35 [&_.obsidian-graph-links_line]:[stroke-linecap:round] [&_.obsidian-graph-links_line]:[stroke-width:1.15] [&_.obsidian-graph-links_line]:transition-[opacity,stroke,stroke-width] [&_.obsidian-graph-links_line]:duration-180 platform-windows:[&_.obsidian-graph-links_line]:transition-none',
    '[&_.obsidian-graph-links_line.is-strong]:stroke-zinc-300/50 [&_.obsidian-graph-links_line.is-strong]:[stroke-width:1.5]',
    '[&_.obsidian-graph-links_line.is-active]:stroke-yellow-300/90 [&_.obsidian-graph-links_line.is-active]:[stroke-width:2.35]',
    '[&_.obsidian-graph-node]:pointer-events-auto [&_.obsidian-graph-node]:cursor-pointer [&_.obsidian-graph-node]:outline-none',
    '[&_.obsidian-graph-node_.node-hit-area]:pointer-events-auto [&_.obsidian-graph-node_.node-hit-area]:fill-transparent',
    '[&_.obsidian-graph-node_.node-glow]:fill-current [&_.obsidian-graph-node_.node-glow]:opacity-[0.08]',
    '[&_.obsidian-graph-node_.node-dot]:fill-current [&_.obsidian-graph-node_.node-dot]:stroke-white/15 [&_.obsidian-graph-node_.node-dot]:opacity-90 [&_.obsidian-graph-node_.node-dot]:[stroke-width:0.8] [&_.obsidian-graph-node_.node-dot]:transition-[r,opacity] [&_.obsidian-graph-node_.node-dot]:duration-180 platform-windows:[&_.obsidian-graph-node_.node-dot]:transition-none',
    '[&_.obsidian-graph-node.node-topico_.node-dot]:opacity-80',
    '[&_.obsidian-graph-node.is-active_.node-dot]:stroke-white/80 [&_.obsidian-graph-node.is-active_.node-dot]:opacity-100 [&_.obsidian-graph-node.is-active_.node-dot]:[stroke-width:1.7] hover:[&_.obsidian-graph-node_.node-dot]:stroke-white/80 hover:[&_.obsidian-graph-node_.node-dot]:opacity-100',
    '[&_.obsidian-graph-node:focus-visible_.node-dot]:stroke-white [&_.obsidian-graph-node:focus-visible_.node-dot]:[stroke-width:3]',
    '[&_.obsidian-graph-node_.node-ring]:fill-none [&_.obsidian-graph-node_.node-ring]:stroke-current [&_.obsidian-graph-node_.node-ring]:[stroke-opacity:0.72] [&_.obsidian-graph-node_.node-ring]:[stroke-width:2]',

    '[&_.obsidian-graph-zoom-controls]:absolute [&_.obsidian-graph-zoom-controls]:top-3.5 [&_.obsidian-graph-zoom-controls]:left-3.5 [&_.obsidian-graph-zoom-controls]:z-[5] [&_.obsidian-graph-zoom-controls]:grid [&_.obsidian-graph-zoom-controls]:gap-1.5 max-[760px]:[&_.obsidian-graph-zoom-controls]:top-2.5 max-[760px]:[&_.obsidian-graph-zoom-controls]:left-2.5',
    '[&_.obsidian-graph-zoom-controls_button]:inline-flex [&_.obsidian-graph-zoom-controls_button]:size-[34px] [&_.obsidian-graph-zoom-controls_button]:cursor-pointer [&_.obsidian-graph-zoom-controls_button]:items-center [&_.obsidian-graph-zoom-controls_button]:justify-center [&_.obsidian-graph-zoom-controls_button]:rounded-[10px] [&_.obsidian-graph-zoom-controls_button]:border [&_.obsidian-graph-zoom-controls_button]:border-white/10 [&_.obsidian-graph-zoom-controls_button]:bg-zinc-900/80 [&_.obsidian-graph-zoom-controls_button]:text-zinc-100 [&_.obsidian-graph-zoom-controls_button]:[backdrop-filter:blur(16px)] hover:[&_.obsidian-graph-zoom-controls_button]:bg-white/12 focus-visible:[&_.obsidian-graph-zoom-controls_button]:bg-white/12 platform-windows:[&_.obsidian-graph-zoom-controls_button]:[backdrop-filter:none]',
    '[&_.obsidian-graph-empty]:grid [&_.obsidian-graph-empty]:h-full [&_.obsidian-graph-empty]:min-h-[520px] [&_.obsidian-graph-empty]:content-center [&_.obsidian-graph-empty]:justify-items-center [&_.obsidian-graph-empty]:gap-2 [&_.obsidian-graph-empty]:p-8 [&_.obsidian-graph-empty]:text-center [&_.obsidian-graph-empty]:text-zinc-400',
    '[&_.obsidian-graph-empty_strong]:text-base [&_.obsidian-graph-empty_strong]:text-zinc-100 [&_.obsidian-graph-empty_p]:m-0 [&_.obsidian-graph-empty_p]:max-w-[380px] [&_.obsidian-graph-empty_p]:text-xs [&_.obsidian-graph-empty_p]:leading-6',

    '[&_.obsidian-memory-card]:absolute [&_.obsidian-memory-card]:top-3.5 [&_.obsidian-memory-card]:right-3.5 [&_.obsidian-memory-card]:z-[4] [&_.obsidian-memory-card]:grid [&_.obsidian-memory-card]:max-h-[calc(100%-28px)] [&_.obsidian-memory-card]:max-w-[340px] [&_.obsidian-memory-card]:gap-[9px] [&_.obsidian-memory-card]:overflow-y-auto [&_.obsidian-memory-card]:rounded-2xl [&_.obsidian-memory-card]:border [&_.obsidian-memory-card]:border-white/8 [&_.obsidian-memory-card]:bg-zinc-900/90 [&_.obsidian-memory-card]:p-3.5 [&_.obsidian-memory-card]:shadow-[0_18px_50px_rgba(0,0,0,0.24)] [&_.obsidian-memory-card]:[backdrop-filter:blur(18px)_saturate(1.15)] max-[760px]:[&_.obsidian-memory-card]:relative max-[760px]:[&_.obsidian-memory-card]:inset-auto max-[760px]:[&_.obsidian-memory-card]:z-[6] max-[760px]:[&_.obsidian-memory-card]:h-full max-[760px]:[&_.obsidian-memory-card]:max-h-none max-[760px]:[&_.obsidian-memory-card]:max-w-none max-[760px]:[&_.obsidian-memory-card]:rounded-[22px_22px_0_0] max-[760px]:[&_.obsidian-memory-card]:border-x-0 max-[760px]:[&_.obsidian-memory-card]:border-b-0 max-[760px]:[&_.obsidian-memory-card]:bg-[#18181b] max-[760px]:[&_.obsidian-memory-card]:px-3.5 max-[760px]:[&_.obsidian-memory-card]:pt-3 max-[760px]:[&_.obsidian-memory-card]:pb-[calc(14px+env(safe-area-inset-bottom))] max-[760px]:[&_.obsidian-memory-card]:shadow-[0_-18px_48px_rgba(0,0,0,0.3)] max-[760px]:[&_.obsidian-memory-card]:[backdrop-filter:none] platform-windows:[&_.obsidian-memory-card]:shadow-none platform-windows:[&_.obsidian-memory-card]:[backdrop-filter:none]',
    'min-[761px]:[&_.obsidian-graph-main.has-selection_.obsidian-memory-card]:relative min-[761px]:[&_.obsidian-graph-main.has-selection_.obsidian-memory-card]:top-auto min-[761px]:[&_.obsidian-graph-main.has-selection_.obsidian-memory-card]:right-auto min-[761px]:[&_.obsidian-graph-main.has-selection_.obsidian-memory-card]:col-start-2 min-[761px]:[&_.obsidian-graph-main.has-selection_.obsidian-memory-card]:m-[14px_14px_86px_0] min-[761px]:[&_.obsidian-graph-main.has-selection_.obsidian-memory-card]:max-h-[calc(100%-100px)] min-[761px]:[&_.obsidian-graph-main.has-selection_.obsidian-memory-card]:max-w-none min-[761px]:[&_.obsidian-graph-main.has-selection_.obsidian-memory-card]:self-start',
    '[&_.obsidian-memory-card-head]:flex [&_.obsidian-memory-card-head]:items-center [&_.obsidian-memory-card-head]:justify-between [&_.obsidian-memory-card-head]:gap-3 [&_.obsidian-memory-card-head>span]:text-[10px] [&_.obsidian-memory-card-head>span]:font-extrabold [&_.obsidian-memory-card-head>span]:tracking-[0.08em] [&_.obsidian-memory-card-head>span]:text-zinc-400 [&_.obsidian-memory-card-head>span]:uppercase [&_.obsidian-memory-card-head>button]:grid [&_.obsidian-memory-card-head>button]:size-8 [&_.obsidian-memory-card-head>button]:cursor-pointer [&_.obsidian-memory-card-head>button]:place-items-center [&_.obsidian-memory-card-head>button]:rounded-full [&_.obsidian-memory-card-head>button]:border [&_.obsidian-memory-card-head>button]:border-white/10 [&_.obsidian-memory-card-head>button]:bg-white/7 [&_.obsidian-memory-card-head>button]:text-zinc-200',
    '[&_.obsidian-memory-card>strong]:text-lg [&_.obsidian-memory-card>strong]:leading-[1.12] [&_.obsidian-memory-card>strong]:text-white [&_.obsidian-memory-card>p]:m-0 [&_.obsidian-memory-card>p]:text-xs [&_.obsidian-memory-card>p]:leading-[1.45] [&_.obsidian-memory-card>p]:text-zinc-300',
    '[&_.obsidian-memory-meta]:grid [&_.obsidian-memory-meta]:gap-1 [&_.obsidian-memory-meta_small]:text-[10px] [&_.obsidian-memory-meta_small]:font-extrabold [&_.obsidian-memory-meta_small]:tracking-[0.08em] [&_.obsidian-memory-meta_small]:text-zinc-400 [&_.obsidian-memory-meta_small]:uppercase',
    '[&_.obsidian-memory-tags]:flex [&_.obsidian-memory-tags]:flex-wrap [&_.obsidian-memory-tags]:gap-[5px] [&_.obsidian-memory-tags_em]:rounded-full [&_.obsidian-memory-tags_em]:border [&_.obsidian-memory-tags_em]:border-yellow-300/15 [&_.obsidian-memory-tags_em]:bg-yellow-300/10 [&_.obsidian-memory-tags_em]:px-[7px] [&_.obsidian-memory-tags_em]:py-1 [&_.obsidian-memory-tags_em]:text-[10px] [&_.obsidian-memory-tags_em]:font-extrabold [&_.obsidian-memory-tags_em]:not-italic [&_.obsidian-memory-tags_em]:text-yellow-200',
    '[&_.obsidian-node-relations]:grid [&_.obsidian-node-relations]:gap-1.5 [&_.obsidian-node-relations]:border-t [&_.obsidian-node-relations]:border-white/7 [&_.obsidian-node-relations]:pt-[9px] [&_.obsidian-node-relations>span]:text-[10px] [&_.obsidian-node-relations>span]:font-[850] [&_.obsidian-node-relations>span]:tracking-[0.08em] [&_.obsidian-node-relations>span]:text-zinc-400 [&_.obsidian-node-relations>span]:uppercase [&_.obsidian-node-relations>small]:text-[10px] [&_.obsidian-node-relations>small]:leading-[1.4] [&_.obsidian-node-relations>small]:text-zinc-500',
    '[&_.obsidian-node-relations_button]:grid [&_.obsidian-node-relations_button]:min-h-10 [&_.obsidian-node-relations_button]:cursor-pointer [&_.obsidian-node-relations_button]:grid-cols-[auto_minmax(0,1fr)] [&_.obsidian-node-relations_button]:items-center [&_.obsidian-node-relations_button]:gap-[7px] [&_.obsidian-node-relations_button]:rounded-[10px] [&_.obsidian-node-relations_button]:border [&_.obsidian-node-relations_button]:border-white/[0.065] [&_.obsidian-node-relations_button]:bg-white/[0.045] [&_.obsidian-node-relations_button]:px-2 [&_.obsidian-node-relations_button]:py-1.5 [&_.obsidian-node-relations_button]:text-left [&_.obsidian-node-relations_button]:text-zinc-100 hover:[&_.obsidian-node-relations_button]:border-yellow-300/20 hover:[&_.obsidian-node-relations_button]:bg-yellow-300/9',
    '[&_.obsidian-node-relations_button>i]:size-[7px] [&_.obsidian-node-relations_button>i]:rounded-full [&_.obsidian-node-relations_button>i]:shadow-[0_0_12px_currentColor] [&_.obsidian-node-relations_button>span]:grid [&_.obsidian-node-relations_button>span]:min-w-0 [&_.obsidian-node-relations_button>span]:gap-px [&_.obsidian-node-relations_button_strong]:overflow-hidden [&_.obsidian-node-relations_button_strong]:text-ellipsis [&_.obsidian-node-relations_button_strong]:whitespace-nowrap [&_.obsidian-node-relations_button_strong]:text-[11px] [&_.obsidian-node-relations_button_small]:overflow-hidden [&_.obsidian-node-relations_button_small]:text-ellipsis [&_.obsidian-node-relations_button_small]:whitespace-nowrap [&_.obsidian-node-relations_button_small]:text-[9px] [&_.obsidian-node-relations_button_small]:text-zinc-400',

    '[&_.obsidian-graph-legend]:absolute [&_.obsidian-graph-legend]:bottom-4 [&_.obsidian-graph-legend]:left-4 [&_.obsidian-graph-legend]:z-[4] [&_.obsidian-graph-legend]:flex [&_.obsidian-graph-legend]:max-w-[calc(100%-32px)] [&_.obsidian-graph-legend]:flex-wrap [&_.obsidian-graph-legend]:items-center [&_.obsidian-graph-legend]:gap-[7px] [&_.obsidian-graph-legend]:rounded-full [&_.obsidian-graph-legend]:border [&_.obsidian-graph-legend]:border-white/8 [&_.obsidian-graph-legend]:bg-zinc-900/75 [&_.obsidian-graph-legend]:p-2 [&_.obsidian-graph-legend]:shadow-[0_18px_50px_rgba(0,0,0,0.24)] [&_.obsidian-graph-legend]:[backdrop-filter:blur(18px)_saturate(1.15)] max-[760px]:[&_.obsidian-graph-legend]:hidden platform-windows:[&_.obsidian-graph-legend]:shadow-none platform-windows:[&_.obsidian-graph-legend]:[backdrop-filter:none]',
    '[&_.obsidian-graph-legend_span]:inline-flex [&_.obsidian-graph-legend_span]:items-center [&_.obsidian-graph-legend_span]:gap-1.5 [&_.obsidian-graph-legend_span]:text-[11px] [&_.obsidian-graph-legend_span]:font-extrabold [&_.obsidian-graph-legend_span]:text-zinc-300 [&_.obsidian-graph-legend_i]:block [&_.obsidian-graph-legend_i]:size-2 [&_.obsidian-graph-legend_i]:rounded-full',
    '[&_.obsidian-graph-stats]:absolute [&_.obsidian-graph-stats]:right-4 [&_.obsidian-graph-stats]:bottom-4 [&_.obsidian-graph-stats]:z-[4] [&_.obsidian-graph-stats]:grid [&_.obsidian-graph-stats]:w-[min(360px,calc(100%-32px))] [&_.obsidian-graph-stats]:grid-cols-4 [&_.obsidian-graph-stats]:gap-1.5 [&_.obsidian-graph-stats]:rounded-2xl [&_.obsidian-graph-stats]:border [&_.obsidian-graph-stats]:border-white/8 [&_.obsidian-graph-stats]:bg-zinc-900/75 [&_.obsidian-graph-stats]:p-2 [&_.obsidian-graph-stats]:shadow-[0_18px_50px_rgba(0,0,0,0.24)] [&_.obsidian-graph-stats]:[backdrop-filter:blur(18px)_saturate(1.15)] max-[760px]:[&_.obsidian-graph-stats]:right-2.5 max-[760px]:[&_.obsidian-graph-stats]:bottom-2.5 max-[760px]:[&_.obsidian-graph-stats]:left-2.5 max-[760px]:[&_.obsidian-graph-stats]:w-auto platform-windows:[&_.obsidian-graph-stats]:shadow-none platform-windows:[&_.obsidian-graph-stats]:[backdrop-filter:none]',
    'min-[761px]:[&_.obsidian-graph-main.has-selection_.obsidian-graph-stats]:right-[354px] min-[761px]:[&_.obsidian-graph-main.has-selection_.obsidian-graph-stats]:w-[min(360px,calc(100%-386px))]',
    'max-[760px]:[&_.obsidian-graph-main.has-selection_.obsidian-graph-stats]:hidden',
    '[&_.obsidian-graph-stats_div]:grid [&_.obsidian-graph-stats_div]:gap-0.5 [&_.obsidian-graph-stats_div]:rounded-xl [&_.obsidian-graph-stats_div]:border [&_.obsidian-graph-stats_div]:border-white/6 [&_.obsidian-graph-stats_div]:bg-white/[0.045] [&_.obsidian-graph-stats_div]:p-2 [&_.obsidian-graph-stats_span]:text-[10px] [&_.obsidian-graph-stats_span]:font-extrabold [&_.obsidian-graph-stats_span]:tracking-[0.08em] [&_.obsidian-graph-stats_span]:text-zinc-400 [&_.obsidian-graph-stats_span]:uppercase [&_.obsidian-graph-stats_strong]:text-lg [&_.obsidian-graph-stats_strong]:leading-none [&_.obsidian-graph-stats_strong]:text-white',

    '[&_.memory-curation-actions]:mt-3 [&_.memory-curation-actions]:grid [&_.memory-curation-actions]:gap-2 [&_.memory-curation-actions_button]:flex [&_.memory-curation-actions_button]:min-h-9 [&_.memory-curation-actions_button]:cursor-pointer [&_.memory-curation-actions_button]:items-center [&_.memory-curation-actions_button]:justify-center [&_.memory-curation-actions_button]:gap-2 [&_.memory-curation-actions_button]:rounded-[14px] [&_.memory-curation-actions_button]:border [&_.memory-curation-actions_button]:border-[var(--liquid-border)] [&_.memory-curation-actions_button]:bg-[var(--liquid-panel-soft)] [&_.memory-curation-actions_button]:px-2.5 [&_.memory-curation-actions_button]:py-2 [&_.memory-curation-actions_button]:text-[var(--text)] [&_.memory-curation-actions_button:disabled]:cursor-progress [&_.memory-curation-actions_button:disabled]:opacity-65',
    '[&_.memory-curation-actions_label]:flex [&_.memory-curation-actions_label]:min-h-9 [&_.memory-curation-actions_label]:items-center [&_.memory-curation-actions_label]:justify-between [&_.memory-curation-actions_label]:gap-2 [&_.memory-curation-actions_label]:rounded-[14px] [&_.memory-curation-actions_label]:border [&_.memory-curation-actions_label]:border-[var(--liquid-border)] [&_.memory-curation-actions_label]:bg-[var(--liquid-panel-soft)] [&_.memory-curation-actions_label]:px-2.5 [&_.memory-curation-actions_label]:py-2 [&_.memory-curation-actions_label]:text-xs [&_.memory-curation-actions_label]:text-[var(--muted)] [&_.memory-curation-actions_input]:min-w-[90px] [&_.memory-curation-actions_input]:flex-1 [&_.memory-curation-actions_input]:accent-[var(--accent-hot)] [&_.memory-curation-actions_.danger]:border-red-400/40 [&_.memory-curation-actions_.danger]:text-red-300 [&_.memory-curation-actions_.error-text]:text-red-300',

    '[&_.brain-stats-popover]:fixed [&_.brain-stats-popover]:top-[74px] [&_.brain-stats-popover]:right-[18px] [&_.brain-stats-popover]:bottom-[18px] [&_.brain-stats-popover]:z-[930] [&_.brain-stats-popover]:grid [&_.brain-stats-popover]:w-[min(440px,calc(100%-44px))] [&_.brain-stats-popover]:max-h-[calc(100dvh-92px)] [&_.brain-stats-popover]:animate-[drawer-in_160ms_cubic-bezier(0.2,0.8,0.2,1)_both] [&_.brain-stats-popover]:gap-3.5 [&_.brain-stats-popover]:overflow-y-auto [&_.brain-stats-popover]:rounded-[28px] [&_.brain-stats-popover]:border [&_.brain-stats-popover]:border-[var(--liquid-border)] [&_.brain-stats-popover]:p-3.5 [&_.brain-stats-popover]:text-[var(--text)] [&_.brain-stats-popover]:shadow-[var(--liquid-shadow-soft)] [&_.brain-stats-popover]:[background:linear-gradient(135deg,var(--liquid-highlight),transparent_42%),var(--liquid-panel)] [&_.brain-stats-popover]:[backdrop-filter:blur(28px)_saturate(1.45)] max-[760px]:[&_.brain-stats-popover]:inset-0 max-[760px]:[&_.brain-stats-popover]:z-[5200] max-[760px]:[&_.brain-stats-popover]:h-dvh max-[760px]:[&_.brain-stats-popover]:w-screen max-[760px]:[&_.brain-stats-popover]:max-h-none max-[760px]:[&_.brain-stats-popover]:rounded-none max-[760px]:[&_.brain-stats-popover]:border-0 max-[760px]:[&_.brain-stats-popover]:bg-[#18181b] max-[760px]:[&_.brain-stats-popover]:px-3 max-[760px]:[&_.brain-stats-popover]:pt-[calc(12px+env(safe-area-inset-top))] max-[760px]:[&_.brain-stats-popover]:pb-[calc(var(--mobile-nav-height)+22px+env(safe-area-inset-bottom))] max-[760px]:[&_.brain-stats-popover]:[backdrop-filter:none] platform-windows:[&_.brain-stats-popover]:animate-none platform-windows:[&_.brain-stats-popover]:shadow-none platform-windows:[&_.brain-stats-popover]:[backdrop-filter:none]',
    '[&_.brain-stats-popover-head]:flex [&_.brain-stats-popover-head]:items-center [&_.brain-stats-popover-head]:justify-between [&_.brain-stats-popover-head]:gap-3 [&_.brain-stats-popover-head>div]:grid [&_.brain-stats-popover-head>div]:gap-[3px] [&_.brain-stats-popover-head_strong]:text-base [&_.brain-stats-popover-head_strong]:text-[var(--text)]',
    '[&_.brain-stats-popover-head_button]:inline-flex [&_.brain-stats-popover-head_button]:min-h-7 [&_.brain-stats-popover-head_button]:cursor-pointer [&_.brain-stats-popover-head_button]:items-center [&_.brain-stats-popover-head_button]:justify-center [&_.brain-stats-popover-head_button]:rounded-full [&_.brain-stats-popover-head_button]:border [&_.brain-stats-popover-head_button]:border-[var(--liquid-border)] [&_.brain-stats-popover-head_button]:bg-[var(--liquid-panel-soft)] [&_.brain-stats-popover-head_button]:px-[9px] [&_.brain-stats-popover-head_button]:text-[var(--text)] hover:[&_.brain-stats-popover-head_button]:border-[var(--liquid-border-strong)] hover:[&_.brain-stats-popover-head_button]:bg-[rgb(var(--accent-hot-rgb)/0.11)]',
    '[&_.brain-user-profile-section]:grid [&_.brain-user-profile-section]:gap-2.5 [&_.brain-user-profile-section]:rounded-[18px] [&_.brain-user-profile-section]:border [&_.brain-user-profile-section]:border-[color-mix(in_srgb,var(--accent-hot),transparent_62%)] [&_.brain-user-profile-section]:bg-[linear-gradient(135deg,rgb(var(--accent-hot-rgb)/0.08),transparent_48%),var(--liquid-panel-soft)] [&_.brain-user-profile-section]:p-3',
    '[&_.brain-profile-memories]:grid [&_.brain-profile-memories]:gap-1.5 [&_.brain-profile-chip]:grid [&_.brain-profile-chip]:grid-cols-[auto_minmax(0,1fr)_auto] [&_.brain-profile-chip]:items-center [&_.brain-profile-chip]:gap-2 [&_.brain-profile-chip]:rounded-xl [&_.brain-profile-chip]:border [&_.brain-profile-chip]:border-[var(--liquid-border)] [&_.brain-profile-chip]:bg-[color-mix(in_srgb,var(--liquid-panel),transparent_14%)] [&_.brain-profile-chip]:px-2.5 [&_.brain-profile-chip]:py-[7px] [&_.brain-profile-chip]:text-xs [&_.brain-profile-chip]:text-[var(--text)] [&_.brain-profile-chip.is-core]:border-[color-mix(in_srgb,var(--accent-hot),transparent_52%)] [&_.brain-profile-chip.is-core]:bg-[color-mix(in_srgb,var(--accent-hot),transparent_88%)] [&_.brain-profile-chip_span]:min-w-0 [&_.brain-profile-chip_span]:overflow-hidden [&_.brain-profile-chip_span]:text-ellipsis [&_.brain-profile-chip_span]:whitespace-nowrap [&_.brain-profile-chip_small]:whitespace-nowrap [&_.brain-profile-chip_small]:text-[11px] [&_.brain-profile-chip_small]:text-[var(--muted)]',
    '[&_.brain-section-label]:mb-0.5 [&_.brain-section-label]:flex [&_.brain-section-label]:items-center [&_.brain-section-label]:gap-1.5 [&_.brain-section-label]:text-[11px] [&_.brain-section-label]:font-bold [&_.brain-section-label]:tracking-[0.06em] [&_.brain-section-label]:text-[var(--muted)] [&_.brain-section-label]:uppercase [&_.brain-section-label_span]:flex-1 [&_.brain-section-label_span]:text-[var(--muted)] [&_.brain-section-label_small]:rounded-full [&_.brain-section-label_small]:border [&_.brain-section-label_small]:border-[var(--liquid-border)] [&_.brain-section-label_small]:bg-[color-mix(in_srgb,var(--liquid-panel),transparent_14%)] [&_.brain-section-label_small]:px-[7px] [&_.brain-section-label_small]:py-px [&_.brain-section-label_small]:text-[10px] [&_.brain-section-label_small]:font-semibold [&_.brain-section-label_small]:tracking-0 [&_.brain-section-label_small]:text-[var(--muted)] [&_.brain-section-label_small]:normal-case',

    '[&_.brain-stats]:grid [&_.brain-stats]:grid-cols-2 [&_.brain-stats]:gap-2 max-[760px]:[&_.brain-stats-popover_.brain-stats]:grid-cols-2',
    '[&_.brain-stat-card]:grid [&_.brain-stat-card]:min-w-0 [&_.brain-stat-card]:gap-1 [&_.brain-stat-card]:rounded-[20px] [&_.brain-stat-card]:border [&_.brain-stat-card]:border-[var(--liquid-border)] [&_.brain-stat-card]:bg-[var(--liquid-panel-soft)] [&_.brain-stat-card]:p-[9px] [&_.brain-stat-card_span]:text-[10px] [&_.brain-stat-card_span]:leading-[1.15] [&_.brain-stat-card_span]:text-[var(--faint)] [&_.brain-stat-card_strong]:font-mono [&_.brain-stat-card_strong]:text-lg [&_.brain-stat-card_strong]:leading-none [&_.brain-stat-card_strong]:text-[var(--text)] [&_.brain-stat-card_small]:text-[10px] [&_.brain-stat-card_small]:leading-[1.25] [&_.brain-stat-card_small]:text-[var(--muted)]',
    '[&_.brain-detail]:grid [&_.brain-detail]:gap-1 [&_.brain-detail]:rounded-[20px] [&_.brain-detail]:border [&_.brain-detail]:border-[var(--liquid-border)] [&_.brain-detail]:bg-[var(--liquid-panel-soft)] [&_.brain-detail]:px-2.5 [&_.brain-detail]:py-[9px] [&_.brain-detail>strong]:flex [&_.brain-detail>strong]:items-center [&_.brain-detail>strong]:gap-1 [&_.brain-detail>strong]:overflow-hidden [&_.brain-detail>strong]:text-ellipsis [&_.brain-detail>strong]:whitespace-nowrap [&_.brain-detail>strong]:font-mono [&_.brain-detail>strong]:text-[13px] [&_.brain-detail>strong]:text-[var(--text)] [&_.brain-detail>p]:m-0 [&_.brain-detail>p]:text-xs [&_.brain-detail>p]:leading-[1.35] [&_.brain-detail>p]:text-[var(--muted)]',
    '[&_.memory-meta-grid]:grid [&_.memory-meta-grid]:grid-cols-2 [&_.memory-meta-grid]:gap-1.5 [&_.memory-meta-grid_small]:rounded-xl [&_.memory-meta-grid_small]:border [&_.memory-meta-grid_small]:border-[var(--liquid-border)] [&_.memory-meta-grid_small]:bg-[var(--liquid-panel-soft)] [&_.memory-meta-grid_small]:px-2 [&_.memory-meta-grid_small]:py-[7px] [&_.memory-meta-grid_small]:text-[var(--muted)]',
    '[&_.recent-learning-strip]:grid [&_.recent-learning-strip]:gap-2 [&_.recent-learning-strip>div:not(.brain-section-label)]:grid [&_.recent-learning-strip>div:not(.brain-section-label)]:grid-cols-[auto_minmax(0,1fr)_auto] [&_.recent-learning-strip>div:not(.brain-section-label)]:items-center [&_.recent-learning-strip>div:not(.brain-section-label)]:gap-x-[9px] [&_.recent-learning-strip>div:not(.brain-section-label)]:gap-y-0.5 [&_.recent-learning-strip>div:not(.brain-section-label)]:rounded-2xl [&_.recent-learning-strip>div:not(.brain-section-label)]:border [&_.recent-learning-strip>div:not(.brain-section-label)]:border-[var(--liquid-border)] [&_.recent-learning-strip>div:not(.brain-section-label)]:bg-[var(--liquid-panel-soft)] [&_.recent-learning-strip>div:not(.brain-section-label)]:p-[9px] [&_.recent-learning-strip>div:not(.brain-section-label)>svg]:row-span-2 [&_.recent-learning-strip>div:not(.brain-section-label)>svg]:text-[var(--accent-hot)] [&_.recent-learning-strip>div:not(.brain-section-label)>strong]:text-xs [&_.recent-learning-strip>div:not(.brain-section-label)>strong]:text-[var(--text)] [&_.recent-learning-strip>div:not(.brain-section-label)>p]:m-0 [&_.recent-learning-strip>div:not(.brain-section-label)>p]:overflow-hidden [&_.recent-learning-strip>div:not(.brain-section-label)>p]:text-ellipsis [&_.recent-learning-strip>div:not(.brain-section-label)>p]:whitespace-nowrap [&_.recent-learning-strip>div:not(.brain-section-label)>p]:text-xs [&_.recent-learning-strip>div:not(.brain-section-label)>p]:text-[var(--muted)] [&_.recent-learning-strip>div:not(.brain-section-label)>small]:col-start-3 [&_.recent-learning-strip>div:not(.brain-section-label)>small]:row-span-2 [&_.recent-learning-strip>div:not(.brain-section-label)>small]:text-[11px] [&_.recent-learning-strip>div:not(.brain-section-label)>small]:text-[var(--faint)]',
    '[&_.learned-source-list]:grid [&_.learned-source-list]:gap-2 [&_.learned-source-list>p]:m-0 [&_.learned-source-list>p]:text-[13px] [&_.learned-source-list>p]:text-[var(--muted)] [&_.learned-source-list>button]:grid [&_.learned-source-list>button]:grid-cols-[auto_minmax(0,1fr)] [&_.learned-source-list>button]:gap-1 [&_.learned-source-list>button]:rounded-2xl [&_.learned-source-list>button]:border [&_.learned-source-list>button]:border-[var(--liquid-border)] [&_.learned-source-list>button]:bg-[var(--liquid-panel-soft)] [&_.learned-source-list>button]:p-2.5 [&_.learned-source-list>button]:text-left [&_.learned-source-list>button]:text-[var(--text)] hover:[&_.learned-source-list>button]:border-[var(--liquid-border-strong)] [&_.learned-source-list>button>span]:grid [&_.learned-source-list>button>span]:min-w-0 [&_.learned-source-list>button>span]:gap-[3px] [&_.learned-source-list_small]:overflow-hidden [&_.learned-source-list_small]:text-ellipsis [&_.learned-source-list_small]:whitespace-nowrap [&_.learned-source-list_small]:text-[var(--muted)]',
    '[&_.memory-type-badge]:inline-block [&_.memory-type-badge]:rounded-full [&_.memory-type-badge]:px-[7px] [&_.memory-type-badge]:py-px [&_.memory-type-badge]:align-middle [&_.memory-type-badge]:text-[10px] [&_.memory-type-badge]:font-bold [&_.memory-type-badge]:tracking-[0.04em] [&_.memory-type-badge]:uppercase [&_.memory-type-badge.type-long]:border [&_.memory-type-badge.type-long]:border-[color-mix(in_srgb,var(--accent-hot),transparent_52%)] [&_.memory-type-badge.type-long]:bg-[color-mix(in_srgb,var(--accent-hot),transparent_82%)] [&_.memory-type-badge.type-long]:text-[var(--accent-hot)] [&_.memory-type-badge.type-medium]:border [&_.memory-type-badge.type-medium]:border-blue-400/45 [&_.memory-type-badge.type-medium]:bg-blue-400/15 [&_.memory-type-badge.type-medium]:text-blue-300 [&_.memory-type-badge.type-short]:border [&_.memory-type-badge.type-short]:border-lime-400/40 [&_.memory-type-badge.type-short]:bg-lime-400/15 [&_.memory-type-badge.type-short]:text-lime-300 [&_.memory-type-badge.type-archive]:border [&_.memory-type-badge.type-archive]:border-zinc-400/35 [&_.memory-type-badge.type-archive]:bg-zinc-400/10 [&_.memory-type-badge.type-archive]:text-zinc-300 [&_.memory-type-badge.type-source]:border [&_.memory-type-badge.type-source]:border-yellow-600/45 [&_.memory-type-badge.type-source]:bg-yellow-600/15 [&_.memory-type-badge.type-source]:text-yellow-400',
    '[&_.concept-list]:grid [&_.concept-list]:gap-[7px] [&_.concept-list_button]:grid [&_.concept-list_button]:min-h-[30px] [&_.concept-list_button]:grid-cols-[minmax(0,1fr)_auto] [&_.concept-list_button]:items-center [&_.concept-list_button]:gap-2 [&_.concept-list_button]:rounded-[var(--radius)] [&_.concept-list_button]:border [&_.concept-list_button]:border-[var(--liquid-border)] [&_.concept-list_button]:bg-[var(--liquid-panel-soft)] [&_.concept-list_button]:px-[9px] [&_.concept-list_button]:text-left [&_.concept-list_button]:text-xs [&_.concept-list_button]:text-[var(--muted)] hover:[&_.concept-list_button]:border-[var(--liquid-border-strong)] hover:[&_.concept-list_button]:text-[var(--text)] [&_.concept-list_button.is-active]:border-[var(--liquid-border-strong)] [&_.concept-list_button.is-active]:text-[var(--text)] [&_.concept-list_button_span]:overflow-hidden [&_.concept-list_button_span]:text-ellipsis [&_.concept-list_button_span]:whitespace-nowrap [&_.concept-list_button_strong]:font-mono [&_.concept-list_button_strong]:text-[11px] [&_.concept-list_button_strong]:text-[var(--accent-hot)]',
  ].join(' '),
} as const
