-- Tabela genérica para sincronização local-first do Nexus IA.
-- Rode no SQL Editor do Supabase antes de ativar o sync.

create table if not exists public.nexus_sync_records (
  id bigint generated by default as identity primary key,
  device_id text not null,
  table_name text not null,
  local_id text not null,
  payload jsonb not null,
  updated_at timestamptz not null,
  synced_at timestamptz not null default now(),
  unique (device_id, table_name, local_id)
);

create index if not exists idx_nexus_sync_records_device
  on public.nexus_sync_records (device_id);

create index if not exists idx_nexus_sync_records_table
  on public.nexus_sync_records (table_name);

create index if not exists idx_nexus_sync_records_updated
  on public.nexus_sync_records (updated_at desc);

alter table public.nexus_sync_records enable row level security;

-- Para uso pessoal/local, você pode liberar leitura e escrita autenticada.
-- Se for distribuir o app, troque por políticas por usuário.
create policy "nexus_sync_select_authenticated"
  on public.nexus_sync_records
  for select
  to authenticated
  using (true);

create policy "nexus_sync_insert_authenticated"
  on public.nexus_sync_records
  for insert
  to authenticated
  with check (true);

create policy "nexus_sync_update_authenticated"
  on public.nexus_sync_records
  for update
  to authenticated
  using (true)
  with check (true);
